### ISSUE TITLE
JSON parser shows error when certain special-character usernames are sent as name, but not as message

### ISSUE THREAD

**Issue by benitoll** [toxic-developer/FiveM-Discord-Bot#11]
Hi,

with certain special-character strings (such as the username **"`^5𝑀𝒾𝑔𝓊𝑒𝓁 ⚡`"**), if they're sent as the message body, they get properly processed and succesfully sent to Discord. 

**__PROPERLY working example event__:**
`TriggerEvent('DiscordBot:ToDiscord', DiscordWebhookSystemInfos, SystemName .. ": " .. server, '```css\n' .. GetPlayerName(source) .. ' connecting\n```', SystemAvatar, false)`

But if they're sent as the name, json.encode fails with `json.exception.parse_error.101` error.

**__Non-working example event__:**
`TriggerEvent('DiscordBot:ToDiscord', Webhook, Name .. ' [ID: ' .. Source .. '] Server: '..server, Message, AvatarURL, false, Source, TTS)`

**__Error info from the console output__:**
`InvokeNative: execution failed: [json.exception.parse_error.101] parse error at line 1, column 49: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"{\"username\":\"𝑀𝒾𝑔𝓊𝑒� '
SCRIPT ERROR: Execution of native 000000008e8cc653 in script host failed.`

I don't want to have to send the usernames in the message body or to force users to change their nicknames, and haven't been able to find a solution to this issue by myself.

this is my first GitHub issue ever, I hope it's properly understable and well made enough.

I hope you can help me, thank you very much.

**Comment by GrimDesignsFiveM** [comment]
This link may help a little more as it's not so much an issue with the code but more so FiveM and Discord all together https://twitter.com/_FiveM/status/1060925945228550144?s=19 as it says in the Error special characters like this ARE NOT utf8 Unicode which is all that FiveM Supports

**Comment by GrimDesignsFiveM** [comment]
Unfortunately in this case having it in the Body or having the users set a UTF8 friendly username is your best bet 👌
