### ISSUE TITLE
Chat Log Issues

### ISSUE THREAD

**Issue by Indep3ndent** [toxic-developer/FiveM-Discord-Bot#13]
Hey, so I've been trying to get everything working for a while and this little thing has not been wanting to function properly. So killing logs, server logs are working perfectly with no issues. Chat log is working 50% correctly. So the OOC/Tweet/AnonTweet/AD Logs are not wanting to go through. Basically everything associated with esx_rpchat is not functioning. I've tried replacing it with other versions of rpchat and entirely using a different chat but nothing seems to work.

Everytime I type one of the above commands I get the following script error.

[https://imgur.com/a/R5De6Ye](url)

I've tried the "HowToFix" you've included at the bottom of the wiki but I'm not sure if I have done it right. I don't think that was the issue though. Any help would be greatly appreciated.

**Comment by GrimDesignsFiveM** [comment]
@Indep3ndent This script is extremely outdated. I will be updating it soon though 👌 in the meantime I will look for a fix for you 😁

You have all your webhooks set up?

**Comment by JakubLudvik** [comment]
> @Indep3ndent This script is extremely outdated. I will be updating it soon though 👌 in the meantime I will look for a fix for you 😁
> 
> You have all your webhooks set up?

Thank you for fixing it and can you make id available for script esx_rpchat_

**Comment by GrimDesignsFiveM** [comment]
@JakubLudvik Do you have Discord? I may have a fix for you!

**Comment by JakubLudvik** [comment]
> @JakubLudvik Do you have Discord? I may have a fix for you!

Yes i have, Jakub#5861, and sorry for my english, im not very good in it.

**Comment by GrimDesignsFiveM** [comment]
@JakubLudvik sent you a friend request

**Comment by GrimDesignsFiveM** [comment]
My discord link is also in the Labels for the issue

**Comment by JakubLudvik** [comment]
@GrimDesignsFiveM Accepted

**Comment by GrimDesignsFiveM** [comment]
Contact me here for fix: https://discord.io/Toxic-Team
